# This file was generated by GoReleaser. DO NOT EDIT.
cask "aitok" do
  version "0.1.22"

  on_macos do
    on_intel do
      sha256 "d7c06a63efa3ce49559d435f2d97f0654d09626f537f68aec9380a053f6f17a1"
      url "https://github.com/MagnumGoYB/aitok/releases/download/v#{version}/aitok_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ef7eb68ed516a2ff9152fbd13fd8c0c382f15e8031778422235cef9a33962a3a"
      url "https://github.com/MagnumGoYB/aitok/releases/download/v#{version}/aitok_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "aitok"
  desc "Offline CLI for summarizing local AI coding token usage"
  homepage "https://github.com/MagnumGoYB/aitok"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aitok"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aitok"]
    end
  end

  # No zap stanza required

end
