# This file was generated by GoReleaser. DO NOT EDIT.
cask "aitok" do
  version "0.1.23"

  on_macos do
    on_intel do
      sha256 "c621dde74dabb344b509f0144dff088a8da306173eacef9269eaa7456b401256"
      url "https://github.com/MagnumGoYB/aitok/releases/download/v#{version}/aitok_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9f188c8003268c6871c9915710dcdc7d4873b6cef96e17a1683a5244fba0c37e"
      url "https://github.com/MagnumGoYB/aitok/releases/download/v#{version}/aitok_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "aitok"
  desc "Offline CLI for summarizing local AI coding token usage"
  homepage "https://github.com/MagnumGoYB/aitok"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aitok"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aitok"]
    end
  end

  # No zap stanza required

end
