# This file was generated by GoReleaser. DO NOT EDIT.
cask "aitok" do
  version "0.1.26"

  on_macos do
    on_intel do
      sha256 "cf612b6a2ce100656a5979ba65843306a415a8c05b6eb2455136601d8b3c38d2"
      url "https://github.com/MagnumGoYB/aitok/releases/download/v#{version}/aitok_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f49781f6b6e13847d3728d52c5d1c02e121dc49c8f1b4a619bc44c01a3b9c483"
      url "https://github.com/MagnumGoYB/aitok/releases/download/v#{version}/aitok_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "aitok"
  desc "Offline CLI for summarizing local AI coding token usage"
  homepage "https://github.com/MagnumGoYB/aitok"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aitok"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aitok"]
    end
  end

  # No zap stanza required

end
